/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface QueryModel {
  query_id?: string;
  user_id?: string;
  created_at_unix_timestamp: number;
  time_to_live_unix_timestamp?: number;
  query_text?: string;
  response_text?: string | null;
  sources?: Array<string>;
}
